image: node:latest

stages:
  - install
  - test

install_dependencies:
  stage: install
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

run_tests:
  stage: test
  script:
    - npx wdio wdio.conf.js
  dependencies:
    - install_dependencies
